/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dashboard3DCard: typeof import('./../components/Dashboard3DCard.vue')['default']
    Empty: typeof import('./../components/Empty.vue')['default']
    GlowBorder: typeof import('./../components/GlowBorder.vue')['default']
    MeteorShower: typeof import('./../components/MeteorShower.vue')['default']
    Page: typeof import('./../components/Page.vue')['default']
    PageTop: typeof import('./../components/PageTop.vue')['default']
    ParentSize: typeof import('./../components/ParentSize.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../components/SearchForm.vue')['default']
    Spline: typeof import('./../components/Spline.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    VoiceTranscription: typeof import('./../components/voice-transcription.vue')['default']
    VortexBackground: typeof import('./../components/VortexBackground.vue')['default']
  }
}
